version: '3.8'

services:
  web:
    build: .
    container_name: resume_builder_web
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/
      - DB_NAME=resume_builder
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./app:/app/app

  mongodb:
    image: mongo:latest
    container_name: resume_builder_mongo
    ports:
      - "27017:27017"
    volumes:
      - resume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  resume:
