apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-builder-ingress
  namespace: resume-builder-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: resume-builder.local # Change this to your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resume-builder-svc
            port:
              number: 80
